title: Новости по мобилизации ученых и лиц с учеными степенями 
subtitle: Новости по мобилизации ученых и лиц с учеными степенями 
github_user:
github_repo_count: 0
github_show_profile_link: false
github_skip_forks: false

