url: http://science-mobilization-news.github.io
title: Новости по мобилизации ученых и лиц с учеными степенями 
subtitle: Web Development in NYC
date_format: "ordinal"
titlecase: true      
github_user:
github_repo_count: 0
github_show_profile_link: false
github_skip_forks: false

